#81/hidden orgnr field
miles-no/miles_web_components pull request #84
Opened 2023-09-14 08:24 UTC by rainow-

2023-09-14 08:36 UTC, skaihigh requested changes

2023-09-14 08:36 UTC, skaihigh commented on src/contact-card/index.js
> +      if (newValue) {
Maybe you should add an extra check to see if orgnr has a length greater than 0.

if (newValue && newValue.length > 0)

2023-10-03 08:21 UTC, knut-hufthammer commented on src/contact-card/index.js
> +      if (newValue) {
LGTM, additional check addressed by https://github.com/miles-no/miles_web_components/pull/84/commits/a53a570979d7368e4aaed72f7ba2a3c29a3b59b7

2023-10-03 08:22 UTC, knut-hufthammer approved these changes
LGTM

2023-10-03 08:28 UTC, merged